#!/usr/bin/env ruby

require 'date'
require 'optparse'

opt = OptionParser.new

params = {}

opt.on('-month:') { |v| params[:month] = v }
opt.on('-year:') { |v| params[:year] = v }

opt.parse!(ARGV)

specified_month = params[:month].to_i
specified_month = Date.today.month if specified_month == 0
specified_year = params[:year].to_i
specified_year = Date.today.year if specified_year == 0
specified_date = Date.new(specified_year, specified_month)
last_day_of_month = Date.new(specified_year, specified_month, -1).day
days = (1..last_day_of_month)
todays_date = Date.today.day

puts "     #{specified_month}月 #{specified_year}"
puts '日 月 火 水 木 金 土'
specified_date.wday.times do
  print '   '
end
days.each do |day|
  if [Date.today.month, Date.today.year] == [specified_month, specified_year] && day == todays_date
    print "\e[47m\e[30m#{todays_date.to_s.rjust(2)}\e[0m "
  else
    print "#{day.to_s.rjust(2)} "
  end
  print "\n" if (day + specified_date.wday) % 7 == 0
end
print "\n"
